/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  DigestSummary,  Link,  NewsletterContent,  NewsletterSection,  NewsletterSummary } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface DigestSummary {
      periodCovered?: string | null
      highlights: string[]
      newsletters: NewsletterSummary[]
      closingNote?: string | null
    }
    export interface Link {
      title?: string | null
      url?: string | null
    }
    export interface NewsletterContent {
      title?: string | null
      publisher?: string | null
      sections: NewsletterSection[]
      topics: string[]
      keyTakeaways: string[]
      links: Link[]
    }
    export interface NewsletterSection {
      heading?: string | null
      summary?: string | null
      importance?: "high" | "medium" | "low" | null
    }
    export interface NewsletterSummary {
      source?: string | null
      headline?: string | null
      summary?: string | null
      topLinks?: Link[] | null
    }
}